### ISSUE TITLE
No such file or directory compilation terminated. Error compiling.

### ISSUE THREAD

**Issue by michaelproino** [TomFreudenberg/udoo-arduino-cli#6]
Hi, I have a problem ; 
No such file or directory compilation terminated. Error compiling.  

I add the library in zip format, correctly, but when I try to run example code, this error occurs, can you help me? ( Windows 8, Arduino Mega2560, Arduino ide 1.6.5 )
![ee](https://cloud.githubusercontent.com/assets/14868198/10130200/f38fec06-65ce-11e5-88a9-40a102f35ded.png)

**Comment by TomFreudenberg** [comment]
Hi @michaelproino - I am sorry, but this is currently only for usage on UDOO boards (http://www.udoo.org) running an DEBIAN or UBUNTU based image.

Cheers
Tom
