### ISSUE TITLE
Compiling for NodeMCU boards?

### ISSUE THREAD

**Issue by dnnagy** [TomFreudenberg/udoo-arduino-cli#7]
Hello. 
First of all thank you for this script. I'm curious if it is possible to compile and upload code to ESP8266 based nodeMCU boards using this script?

**Comment by TomFreudenberg** [comment]
Hi Nagi ( @kommancs96 )

I am sorry but I do not have any know how of this board.

I close this issue but feel free to use it and continue communication.

Cheers
Tom
